[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "cd backend/scrapers && npm install"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python backend_api/main.py" 